title: Collected theme
description: Collected is a theme devoted to short-form, commonplace style posts.
owner_name: Jekyll Collected Theme
owner_homepage: https://github.com/joebuhlig/jekyll-theme-collected
